# Generated by Django 6.0.6 on 2026-07-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedCartReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("FIRST", "First reminder"),
                            ("SECOND", "Second reminder"),
                            ("FINAL", "Final reminder"),
                        ],
                        default="FIRST",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recovered",
                    models.BooleanField(
                        default=False,
                        help_text="Did the user place an order after this reminder?",
                    ),
                ),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="cart.cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abandoned Cart Reminder",
                "verbose_name_plural": "Abandoned Cart Reminders",
                "ordering": ("-sent_at",),
                "indexes": [
                    models.Index(
                        fields=["cart", "reminder_type"],
                        name="cart_abando_cart_id_1b6454_idx",
                    )
                ],
            },
        ),
    ]
